<div class="row">
    <div class="col-md-12">
        <div class="well">
            <p>Are you sure to delete this book?</p>
            <p>
            <form action="" method="post">
                <input type="hidden" name="csrf" value="<?= $csrf ?>">
                <input type="submit" class="btn btn-danger" value="Yes, Delete">
                <a class="btn btn-primary" href="/book">Cancel</a>
            </form>
            </form>
            </p>
        </div>

    </div>
</div>

